config/routes.rb
PracticeApp2::Application.routes.draw do
  devise_for :users

  resources :home
  resources :rss_feeds

   root :to => 'home#index'

end

app/models/rss_feed.rb
class RssFeed < ActiveRecord::Base
  has_many :user_feeds
  has_many :users, :through => :user_feeds
  attr_accessible :url

  searchable do
    text:url
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_feeds
  has_many :rss_feeds, :through => :user_feeds
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user_feed.rb
class UserFeed < ActiveRecord::Base
  belongs_to :rss_feeds
  belongs_to :users
  attr_accessible :user_id, :rss_feed_id
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @session = user_signed_in?
    @user = current_user

    feeds = Array.new

    @rss_feed = RssFeed.all
    @rss_feed.each do |feed|
      url = feed.url #get the url of the feed from the rss_feed table where the feedID matches
      parsedFeed = Feedjira::Feed.fetch_and_parse url # parse the xml
      feeds.push(parsedFeed)  # push the parsed xml in the feeds array
    end
    @rss_feeds = feeds
  end

end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
  before_filter :authenticate_user!

  def index

    @session = user_signed_in?
    @user = current_user

    feeds = Array.new
    urlArray = Array.new

    @user_feed = UserFeed.where(user_id: current_user.id) #get the rss feedID from the table user_feed for the current user ID

    @user_feed.each do |feed|
      url = RssFeed.where(id: feed.rss_feed_id).first.url #get the url of the feed from the rss_feed table where the feedID matches
      urlArray.push(url)
      parsedFeed = Feedjira::Feed.fetch_and_parse url # parse the xml
      feeds.push(parsedFeed)  # push the parsed xml in the feeds array
    end
    @rss_feeds = feeds
    @feeds_url = urlArray
    #Searching a feed by it's url
    if params[:search]==nil
      @searched_rss_feeds = []
    else
      searchfeeds = Array.new
      @search = RssFeed.search do
        fulltext params[:search]
      end
      @searched_rss_feeds = @search.results
      @searched_rss_feeds.each do |sfeed|
        url = sfeed.url
        parsedFeed = Feedjira::Feed.fetch_and_parse url # parse the xml
        searchfeeds.push(parsedFeed)  # push the parsed xml in the searchfeeds array
      end
      @searched_rss_feeds = searchfeeds
    end




  end

  def new
    @session = user_signed_in?
    @user = current_user
    @rss_feed = RssFeed.new
  end

  def create
    @session = user_signed_in?
    @user = current_user
    @user =  current_user.id
    @rss_feed =RssFeed.where(params[:rss_feed])

    if @rss_feed.present? #if the rss feed url already present in the rss_feed table
      @user_feed = UserFeed.where(user_id: @user, rss_feed_id: rss_feed.first.id)
      if @user_feed.present?  #if the user has already applied for that feed
        render 'new'
      else#else-if the user is applying for a new feed
        @user_feed = UserFeed.new user_id: @user, rss_feed_id: @rss_feed.first.id
      end
      @user_feed.save

  else  #else-if the user entered a completely new rss feed url
    @rss_feed = RssFeed.new(params[:rss_feed])
    @rss_feed.save
    @user_feed = UserFeed.new user_id: @user, rss_feed_id: @rss_feed.id
    @user_feed.save
  end

    redirect_to rss_feeds_path
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>Hello World </h2>
<%= link_to 'Feeds', rss_feeds_path %>
<% @rss_feeds.each do |feed| %>
  <div class="feedDiv" style="float:left;width:45%;clear:none">
    <h2 class="feedHeading">
      <%= link_to feed.url do%><%= feed.title %><% end %>
    </h2>

  <div class="feedEntry" style="width:90%">
    <h3 ><%=link_to feed.entries.first.title, feed.entries.first.url,{:style=>"color:black"} %></h3>
    <p><%= feed.entries.first.published %></p>
    <p><%=raw feed.entries.first.summary %></p>
  </div>

</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeApp2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if @session %>
  <div class="header">
    <div style="float:left">Logged in as: <%= @user.email %></div>
    <div style="float:right"><%= button_to "Sign out", destroy_user_session_path, :method => :delete %></div>
  </div>
  <nav class="nav">
    <span  class="appName">FeedZone</span>
    <ul class="navul">
      <%= link_to home_index_path do %><li>Home</li><% end  %>
      <%= link_to rss_feeds_path do %><li>My Feeds</li><% end %>
      <a href="#" style="width:12%"><li onclick="showSubMenu(manageFeedsSub)">Manage Feeds  ></li></a>
      <div id="manageFeedsSub" style="display:none;float:left">
        <%= link_to new_rss_feed_path do %><li>Add Feeds</li><% end %>
      </div>
    </ul>



  </nav>

<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/rss_feeds/index.html.erb
<%= form_tag rss_feeds_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search], {:placeholder=>'Search for url'} %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<%if @searched_rss_feeds.present? %>
  <h1>Search Results:</h1>
  <ol>
  <% @searched_rss_feeds.each do |sfeed|%>
    <li class="feedHeading">
      <%= link_to sfeed.url do%><%= sfeed.title %><% end %>
    </li>
  <% end %>
</ol>
  <hr>
<% end %>

<% @rss_feeds.each_with_index do |feed, index| %>
  <div class="feedDiv">
    <h2 class="feedHeading">
      <%= link_to feed.url do%>
        <%= feed.title %><small> url: <%= @feeds_url[index] %></small>
      <% end %>
    </h2>
  <% feed.entries.each do |entry| %>
    <div class="feedEntry">
      <h3 ><%=link_to entry.title, entry.url,{:style=>"color:black"} %></h3>
      <p><%= entry.published %></p>
      <p><%=raw entry.summary %></p>
    </div>
  <% end %>
</div>
<% end %>

app/views/rss_feeds/new.html.erb
<h2>Feeds</h2>
<%= form_for :rss_feed, :url => {:action => "create"} do |f| %>
  <p>
    <%= f.label 'URL' %>
    <%= f.text_field 'url' %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'back', rss_feeds_path,{:style=>'color:blue'} %>

app/views/rss_feeds/show.html.erb
<%= @rss_feed.title %>